version: '3.7'

services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./realestatedb_init.sql:/tmp/realestatedb_init.sql
      - ./init_docker_postgres.sh:/docker-entrypoint-initdb.d/init_docker_postgres.sh
    environment:
      - POSTGRES_USER=alex
      - POSTGRES_PASSWORD=alex123456
      - POSTGRES_DB=realestatedb
  pgadmin:
    image: dpage/pgadmin4
    environment: 
        PGADMIN_DEFAULT_EMAIL: "a@a.com"
        PGADMIN_DEFAULT_PASSWORD: "123456"
    ports: 
        - "8001:80"
    depends_on: 
        - db

volumes:
  postgres_data: