version: '3.7'

services:
  web:
    image: web-prod
    command: gunicorn realEstate.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./realestatedb_init.sql:/tmp/realestatedb_init.sql
      - ./init_docker_postgres.sh:/docker-entrypoint-initdb.d/init_docker_postgres.sh
    env_file:
      - ./.env.prod.db
  nginx:
    image: nginx-prod
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
      - ./nginx/certbot/www:/var/www/certbot  # for the validation challenges
      - ./nginx/certbot/conf:/etc/letsencrypt # for ssl certificates
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - web
  certbot:
    image: certbot/certbot
    volumes:
      - ./nginx/certbot/www:/var/www/certbot
      - ./nginx/certbot/conf:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  static_volume:
  media_volume: